"""Pylint checker: enforce structlog usage over stdlib logging."""

from __future__ import annotations

from pathlib import Path

from astroid import nodes
from pylint.checkers import BaseChecker
from pylint.lint import PyLinter

from python_setup_lint.checkers._base import LintRuleId, MessageDef

class StructlogChecker(BaseChecker):
    name: str = "structlog-checker"
    msgs: dict[LintRuleId, MessageDef]
    options: tuple[tuple[str, dict], ...]

    def __init__(self, linter: PyLinter) -> None: ...
    def open(self) -> None: ...
    def visit_module(self, _node: nodes.Module) -> None: ...
    def visit_call(self, node: nodes.Call) -> None: ...
    def _check_logging_getlogger(self, node: nodes.Call) -> None: ...
    def _check_logger_method_call(self, node: nodes.Call) -> None: ...
    @staticmethod
    def _get_node_file_path(node: nodes.NodeNG) -> Path | None: ...
    @staticmethod
    def _has_format_spec(s: str) -> bool: ...

def register(linter: PyLinter) -> None: ...
