"""Unit tests for the semantic meaningful checker threshold.

Tests that ``check_if_meaningful`` correctly distinguishes meaningful
justifications from meaningless ones using the heuristic fallback
(no model download required, no ``@pytest.mark.slow``).
"""

from __future__ import annotations

from unittest.mock import patch

import pytest

from python_setup_lint.checkers._base import check_if_meaningful

# ── Threshold test: 50+ calls ────────────────────────────────────────


class TestSemanticThreshold:
    """Exercises ``check_if_meaningful`` with >50 realistic comments.

    The semantic NLP pipeline is disabled via environment variable so
    the heuristic fallback is always used — no model download, no cache,
    no ``@pytest.mark.slow`` marker needed.
    """

    # ── Meaningful comments (should return True) ──────────────────────

    @pytest.mark.parametrize(
        "comment",
        [
            # Technical code-review justifications
            "circular import — PyLinter not available at runtime",
            "type stub not yet generated for this module",
            "third-party library has no type stubs available",
            "conditional import guarded by TYPE_CHECKING",
            "runtime attribute set by C extension, not visible to pylint",
            "this module is generated by protobuf compiler",
            "import is only used for type checking, not at runtime",
            "function is overridden in subclass with different signature",
            "variable assigned in except handler, not defined in all paths",
            "nested function closure captures variable by reference",
            "abstract method implemented in concrete subclass",
            "property setter defined in parent class",
            "metaclass conflict resolved at runtime",
            "dynamic attribute set by __getattr__",
            "module-level __all__ controls public API",
            "re-export for backwards compatibility",
            "alias for renamed external dependency",
            "conditional import for Python version compatibility",
            "platform-specific code path for Windows",
            "mock object used in test fixture setup",
            "fixture parameter injected by pytest",
            "async generator needs manual cleanup in __aenter__",
            "context manager wraps low-level resource handle",
            "descriptor protocol implemented via __set_name__",
            "singleton pattern uses __new__ override",
            "dataclass field with default_factory",
            "enum member with custom __init__ parameters",
            "mixin class designed for cooperative multiple inheritance",
            "abstract property defined in ABC base class",
            "classmethod used as alternative constructor",
        ],
    )
    def test_meaningful_comment(self, comment: str) -> None:
        """A genuinely meaningful justification should pass."""
        with patch.dict("os.environ", {"PYTHON_SETUP_LINT_SEMANTIC": "0"}):
            result = check_if_meaningful(comment)
        assert result is True, f"Expected True for meaningful comment: {comment!r}"

    # ── Meaningless comments (should return False) ────────────────────

    @pytest.mark.parametrize(
        "comment",
        [
            # Placeholder / vague single words
            "TODO",
            "fix this",
            "need to check",
            "maybe later",
            "not sure",
            "hmm",
            "???",
            "lol",
            "wtf",
            "nice",
            "good",
            "bad",
            "ok",
            "done",
            "fixed",
            "works",
            "broken",
            "test",
            "check",
            "update",
            "remove",
            "add",
            "change",
            "fix",
            "improve",
            "refactor",
            # Boilerplate
            "noqa",
            "ignore",
            "suppress",
            "disable",
            "skip",
            "todo",
            "fixme",
            "hack",
            # Short / empty-like
            "a",
            "ab",
            "abc",
            "xyz",
            "n/a",
            "na",
            "none",
            "nil",
            "null",
            "void",
            "blank",
            "empty",
            "tbd",
            "wip",
            "temp",
            "tmp",
        ],
    )
    def test_meaningless_comment(self, comment: str) -> None:
        """A meaningless justification should fail."""
        with patch.dict("os.environ", {"PYTHON_SETUP_LINT_SEMANTIC": "0"}):
            result = check_if_meaningful(comment)
        assert result is False, f"Expected False for meaningless comment: {comment!r}"
