[mypy]
exclude = test/data/
strict = true

[mypy-astroid.*]
ignore_missing_imports = True

[mypy-luqum.*]
follow_untyped_imports = true

[mypy-pylint.*]
ignore_missing_imports = True

[mypy-beartype.*]
ignore_missing_imports = True

[mypy-structlog.*]
ignore_missing_imports = True
