"""Stub for :mod:`python_setup_lint.runner._record_parsers`.

Per-tool violation-record parsers (T2 baseline diff).
"""


from ._record_types import Record

def _parse_pylint_records(stdout: str) -> list[Record]: ...
def _parse_ruff_records(stdout: str) -> list[Record]: ...
def _parse_mypy_records(stdout: str) -> list[Record]: ...
def _parse_ty_records(stdout: str) -> list[Record]: ...
def _parse_yamllint_records(stdout: str) -> list[Record]: ...
def _parse_rumdl_records(stdout: str) -> list[Record]: ...
def _parse_pyright_records(data: object) -> list[Record]: ...


def _parse_pyright_check_records(stdout: str) -> list[Record]:
    """Parse pyright --outputjson output from a string."""


